from __future__ import annotations

from dataclasses import dataclass
from typing import Any
from urllib.parse import urlparse


@dataclass(frozen=True, slots=True)
class OpenAICompatibleAltTextConfig:
    endpoint: str
    api_key: str
    model: str
    timeout_seconds: int


@dataclass(slots=True)
class OpenAICompatibleAltTextGenerator:
    config: OpenAICompatibleAltTextConfig

    def generate_alt_text(self, *, image_url: str) -> str | None:
        client = _build_openai_client(
            api_key=self.config.api_key,
            base_url=_to_base_url(self.config.endpoint),
            timeout=self.config.timeout_seconds,
        )

        response: Any = client.responses.create(
            model=self.config.model,
            input=[
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "input_text",
                            "text": (
                                "Write concise accessibility alt text for the image. "
                                "Return only the alt text sentence with no surrounding quotes."
                            ),
                        },
                        {
                            "type": "input_image",
                            "image_url": image_url,
                        },
                    ],
                },
            ],
        )

        output_text = getattr(response, "output_text", None)
        if not isinstance(output_text, str):
            return None
        stripped = output_text.strip()
        text_with_disclaimer = (
            stripped
            + " [alt text generated by a large language model; may be inaccurate]"
        )
        return text_with_disclaimer if text_with_disclaimer else None


def _build_openai_client(*, api_key: str, base_url: str, timeout: int) -> Any:
    import openai

    return openai.OpenAI(
        api_key=api_key,
        base_url=base_url,
        timeout=timeout,
    )


def _to_base_url(endpoint_or_base: str) -> str:
    trimmed = endpoint_or_base.strip().rstrip("/")
    if not trimmed:
        raise ValueError("ALT_GEN_ENDPOINT must not be empty")

    if trimmed.endswith("/responses"):
        return trimmed[: -len("/responses")]

    if trimmed.endswith("/chat/completions"):
        return trimmed[: -len("/chat/completions")]

    parsed = urlparse(trimmed)
    path = parsed.path.rstrip("/")
    if path.endswith("/v1"):
        return trimmed

    return f"{trimmed}/v1"
